# Generated by Django 4.1.7 on 2023-04-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_converted_date_lead_date_added_lead_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='date_added',
        ),
    ]
